import Head from 'next/head'
import Image from "next/image";
import logo from '../img/cooltext412050815753570.png'
import Link from "next/link";

const Layout = ({children}) => {
  return (
    <div >
      <Head>
        <title>dbdtierlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/flowbite@1.4.3/dist/flowbite.min.css"
        />
        <script src='https://unpkg.com/@mui/material@5.6.3/umd/material-ui.development.js'></script>
        <script src="https://unpkg.com/flowbite@1.4.3/dist/flowbite.js"></script>
      </Head>

      <div className="min-h-screen h-full bg-zinc-800 w-full flex flex-col items-center">
        <div className="min-h-full w-full">
          <nav className="bg-neutral-900">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex items-center justify-center h-16">
                <div className="flex items-center self-center">
                  <div className="flex-shrink-0 justify-center items-center pt-2">
                    <Image
                      className=""
                      src={logo}
                      width={250}
                      height={35}
                      alt="logo"
                    />
                  </div>
                  <div className="hidden md:block">
                    <div className="ml-10 flex items-baseline space-x-4">
                      <a
                        href="/killers"
                        className="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium"
                        aria-current="page"
                      >
                        Killers
                      </a>

                      <a
                        href="/perks/killers"
                        className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                      >
                        Killers Perks
                      </a>

                      <a
                        href="/survivors"
                        className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                      >
                        Survivors
                      </a>

                      <a
                        href="/perks/survivors"
                        className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                      >
                        Survivors Perks
                      </a>
                      <a
                          href="/randomizer/killer"
                          className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                      >
                        Randomizer
                      </a>


                    </div>
                  </div>
                </div>

                <div className="-mr-2 flex md:hidden">
                  <button
                    type="button"
                    className="bg-gray-800 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                    aria-controls="mobile-menu"
                    aria-expanded="false"
                  >
                    <span className="sr-only">Open main menu</span>

                    <svg
                      className="block h-6 w-6"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      aria-hidden="true"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M4 6h16M4 12h16M4 18h16"
                      />
                    </svg>

                    <svg
                      className="hidden h-6 w-6"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      aria-hidden="true"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M6 18L18 6M6 6l12 12"
                      />
                    </svg>
                  </button>
                </div>
              </div>
            </div>

            <div className="md:hidden" id="mobile-menu">
              <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
                <a
                  href="#"
                  className="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium"
                  aria-current="page"
                >
                  Killers
                </a>

                <a
                  href="#"
                  className="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Killers Perks
                </a>

                <a
                  href="#"
                  className="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Survivors
                </a>

                <a
                  href="#"
                  className="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Survivors Perks
                </a>
              </div>
            </div>
          </nav>
        </div>

        {children}
        {/* <TierWrapperHoc
          TierChar={"S"}
          TierMainColor={"red-700"}
          TierSecondaryColor={"red-400"}
        >
          <AnimatePresence>
            <div className="flex">
              <Card TierMainColor={"red-700"} TierSkullImg={KillerRedRankImg} />

            </div>
          </AnimatePresence>
        </TierWrapperHoc>
        <TierWrapperHoc
          TierChar={"A"}
          TierMainColor={"purple-700"}
          TierSecondaryColor={"purple-400"}
        >
          <AnimatePresence>
            <div className="flex">
              <Card TierMainColor={"purple-700"} TierSkullImg={KillerPurpleRankImg}/>
            </div>
          </AnimatePresence>
        </TierWrapperHoc>
        <TierWrapperHoc
          TierChar={"B"}
          TierMainColor={"green-700"}
          TierSecondaryColor={"green-400"}
        >
          <AnimatePresence>
            <div className="flex">
              <Card TierMainColor={"green-700"} TierSkullImg={KillerYellowRankImg}/>

            </div>
          </AnimatePresence>
        </TierWrapperHoc>

        <TierWrapperHoc
          TierChar={"C"}
          TierMainColor={"stone-700"}
          TierSecondaryColor={"stone-700"}
        >
          <AnimatePresence>
            <div className="flex">
              <Card TierMainColor={"stone-700"} TierSkullImg={KillerYellowRankImg}/>

            </div>
          </AnimatePresence>
        </TierWrapperHoc> */}
      </div>

      <footer ></footer>
    </div>
  )
}

export default Layout
